In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [9]:
import time


a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(a)
print(b)
print(c)
print('Vectorized version: '+ str(1000 *(toc - tic)) +'ms' )

[0.2776512  0.25500511 0.55865725 ... 0.82245676 0.29353895 0.16100687]
[0.39036542 0.26419005 0.46827504 ... 0.73070579 0.89064656 0.57482841]
250033.45187422892
Vectorized version: 1.001596450805664ms


In [4]:
c = 0
tic = time.time()
for i in range (1000000):
    c += a[i] * b[i]
    
toc = time.time()
print(c)
print('For loop: ' + str(1000 * (toc - tic)) + 'ms')

249946.28105302204
For loop: 271.3465690612793ms


In [5]:
x=np.array([[[1],[2]],[[3],[4]]])

In [6]:
x.shape

(2, 2, 1)

In [8]:
a=np.array([[2,1],[1,3]])
b= np.dot(a,a)
b

array([[ 5,  5],
       [ 5, 10]])